// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	user_gorm "github.com/mtroym/evmonitor/biz/router/user_gorm"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user_gorm.Register(r)
}
